In [187]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import plotly
import seaborn as sns; sns.set()
from matplotlib import dates
import altair as alt
import math

In [188]:
#read the csv and show the head
jedi = pd.read_csv('jedi_v1_og.csv', low_memory=False)
jedi.head()

Event #    GOES Flare Start Time     GOES Flare Peak Time GOES Flare Class  \
0      1.0  2010-05-04 16:15:00.000  2010-05-04 16:29:00.000             C3.6   
1      2.0  2010-05-05 07:09:00.000  2010-05-05 07:16:00.000             C2.3   
2      3.0  2010-05-05 11:37:00.000  2010-05-05 11:52:00.000             C8.8   
3      4.0  2010-05-05 17:13:00.000  2010-05-05 17:19:00.000             M1.2   
4      5.0  2010-05-07 07:29:00.000  2010-05-07 07:42:00.000             C2.0   

      Pre-Flare Start Time       Pre-Flare End Time Flare Interrupt  \
0  2010-05-04 08:29:00.000  2010-05-04 16:29:00.000            True   
1  2010-05-04 23:16:00.000  2010-05-05 07:16:00.000            True   
2  2010-05-04 23:16:00.000  2010-05-05 07:16:00.000            True   
3  2010-05-04 23:16:00.000  2010-05-05 07:16:00.000           False   
4  2010-05-06 23:42:00.000  2010-05-07 07:42:00.000            True   

   9.4 Pre-Flare Irradiance [W/m2]  13.1 Pre-Flare Irradiance [W/m2]  \
0                              NaN                               NaN   
1                         0.000004                          0.000002   
2                         0.000004                          0.000002   
3                         0.000004                          0.000002   
4                              NaN                               NaN   

   13.3 Pre-Flare Irradiance [W/m2]              ...               \
0                               NaN              ...                
1                               NaN              ...                
2                               NaN              ...                
3                               NaN              ...                
4                               NaN              ...                

   103.2 by 63.0 Fitting Score  103.2 by 71.9 Fitting Score  \
0                          NaN                          NaN   
1                          NaN                          NaN   
2                          NaN                          NaN   
3                          NaN                          NaN   
4                          NaN                          NaN   

   103.2 by 72.2 Fitting Score  103.2 by 77.0 Fitting Score  \
0                          NaN                          NaN   
1                          NaN                          NaN   
2                          NaN                          NaN   
3                          NaN                          NaN   
4                          NaN                          NaN   

   103.2 by 79.0 Fitting Score  103.2 by 83.6 Fitting Score  \
0                          NaN                          NaN   
1                          NaN                          NaN   
2                          NaN                          NaN   
3                          NaN                          NaN   
4                          NaN                          NaN   

   103.2 by 95.0 Fitting Score  103.2 by 97.3 Fitting Score  \
0                          NaN                          NaN   
1                          NaN                          NaN   
2                          NaN                          NaN   
3                          NaN                          NaN   
4                          NaN                          NaN   

   103.2 by 97.7 Fitting Score  103.2 by 102.6 Fitting Score  
0                          NaN                           NaN  
1                          NaN                           NaN  
2                          NaN                           NaN  
3                          NaN                           NaN  
4                          NaN                           NaN  

[5 rows x 24304 columns]

In [189]:
jedi_sub = jedi[['19.5 Depth [%]', '17.1 Depth [%]', '30.4 Depth [%]', '21.1 Depth [%]']]

In [190]:
def index_of_nans(values):
    """returns an array that contains the indices of when the elements equal nan, must pass it a 2d numpy array"""
    useless_euvs = []
    for index, elem in enumerate(values):
        if math.isnan(elem):
            useless_euvs.append(index)
    
    return useless_euvs

In [191]:
ind_of_empty_events = index_of_nans(jedi_sub.T.describe().values[1])

In [192]:
event_num = jedi.filter(regex='Event #')
GOES_flare_data= jedi.filter(regex='GOES Flare ')
pre_flare_start = jedi.filter(regex='Pre-Flare Start Time')
pre_flare_end = jedi.filter(regex='Pre-Flare End Time')
flare_interrupt = jedi.filter(regex='Flare Interrupt')

type(event_num)

pandas.core.frame.DataFrame

In [193]:
useless_event_nums = []
for i in range(len(ind_of_empty_events)):
    for k in range(len(jedi_sub)):
        if ind_of_empty_events[i] == k:
            useless_event_nums.append(event_num.values[k])

In [194]:
jedi_sub.head(10)

19.5 Depth [%]  17.1 Depth [%]  30.4 Depth [%]  21.1 Depth [%]
0             NaN             NaN             NaN             NaN
1             NaN             NaN             NaN             NaN
2             NaN             NaN             NaN             NaN
3             NaN             NaN        0.093239             NaN
4             NaN             NaN             NaN             NaN
5             NaN             NaN             NaN             NaN
6             NaN             NaN             NaN             NaN
7             NaN        0.420038             NaN             NaN
8             NaN        0.900706        0.054656             NaN
9             NaN        0.235694        0.105876             NaN

In [195]:
jedi_sub.describe()

19.5 Depth [%]  17.1 Depth [%]  30.4 Depth [%]  21.1 Depth [%]
count      343.000000      338.000000      621.000000      319.000000
mean         1.616278        1.557309        0.641082        1.639358
std          1.948313        1.525887        0.893133        2.086991
min          0.000333        0.002962        0.000526        0.006233
25%          0.376743        0.421045        0.130372        0.287005
50%          1.012425        1.096147        0.342509        0.824832
75%          2.062317        2.122782        0.714671        2.028294
max         13.024037        8.871504        6.777720       11.151263

In [196]:
#watch out if you run this more than once, end with the a weird recursion-ish problem
# DONT RUN AGAIN
frames = [event_num, GOES_flare_data, pre_flare_start, pre_flare_end, flare_interrupt, jedi_sub]
jedi_sub_v2 = pd.concat(frames, axis=1)


In [197]:
jedi_sub_copy = jedi_sub_v2.copy()

In [198]:
useless_event_nums

[array([1.]),
 array([2.]),
 array([3.]),
 array([5.]),
 array([6.]),
 array([7.]),
 array([12.]),
 array([13.]),
 array([14.]),
 array([15.]),
 array([16.]),
 array([17.]),
 array([22.]),
 array([25.]),
 array([26.]),
 array([35.]),
 array([37.]),
 array([37.]),
 array([39.]),
 array([42.]),
 array([43.]),
 array([44.]),
 array([46.]),
 array([52.]),
 array([52.]),
 array([52.]),
 array([52.]),
 array([53.]),
 array([53.]),
 array([55.]),
 array([58.]),
 array([58.]),
 array([59.]),
 array([59.]),
 array([62.]),
 array([64.]),
 array([65.]),
 array([66.]),
 array([67.]),
 array([68.]),
 array([69.]),
 array([72.]),
 array([72.]),
 array([73.]),
 array([73.]),
 array([74.]),
 array([74.]),
 array([75.]),
 array([76.]),
 array([77.]),
 array([83.]),
 array([83.]),
 array([85.]),
 array([91.]),
 array([95.]),
 array([96.]),
 array([97.]),
 array([101.]),
 array([102.]),
 array([103.]),
 array([104.]),
 array([105.]),
 array([106.]),
 array([107.]),
 array([108.]),
 array([112.]),
 array(

In [199]:
jedi_sub_copy

Event #    GOES Flare Start Time     GOES Flare Peak Time  \
0         1.0  2010-05-04 16:15:00.000  2010-05-04 16:29:00.000   
1         2.0  2010-05-05 07:09:00.000  2010-05-05 07:16:00.000   
2         3.0  2010-05-05 11:37:00.000  2010-05-05 11:52:00.000   
3         4.0  2010-05-05 17:13:00.000  2010-05-05 17:19:00.000   
4         5.0  2010-05-07 07:29:00.000  2010-05-07 07:42:00.000   
5         6.0  2010-05-08 04:51:00.000  2010-05-08 04:59:00.000   
6         7.0  2010-05-08 11:40:00.000  2010-05-08 11:50:00.000   
7         9.0  2010-06-12 00:30:00.000  2010-06-12 00:57:00.000   
8        10.0  2010-06-12 03:57:00.000  2010-06-12 04:06:00.000   
9        11.0  2010-06-12 09:02:00.000  2010-06-12 09:17:00.000   
10       12.0  2010-06-13 05:30:00.000  2010-06-13 05:39:00.000   
11       13.0  2010-06-13 06:08:00.000  2010-06-13 06:11:00.000   
12       14.0  2010-06-13 07:05:00.000  2010-06-13 07:08:00.000   
13       15.0  2010-06-13 07:31:00.000  2010-06-13 07:34:00.000   
14       16.0  2010-06-13 08:06:00.000  2010-06-13 08:13:00.000   
15       17.0  2010-06-13 09:41:00.000  2010-06-13 09:46:00.000   
16       18.0  2010-06-13 10:47:00.000  2010-06-13 10:53:00.000   
17       19.0  2010-06-14 00:44:00.000  2010-06-14 00:51:00.000   
18       20.0  2010-07-08 22:03:00.000  2010-07-08 22:16:00.000   
19       21.0  2010-07-09 08:53:00.000  2010-07-09 09:01:00.000   
20       22.0  2010-07-09 19:26:00.000  2010-07-09 19:51:00.000   
21       23.0  2010-07-13 10:43:00.000  2010-07-13 10:51:00.000   
22       24.0  2010-07-14 12:11:00.000  2010-07-14 12:30:00.000   
23       25.0  2010-07-14 20:31:00.000  2010-07-14 20:47:00.000   
24       26.0  2010-07-17 17:27:00.000  2010-07-17 18:01:00.000   
25       27.0  2010-07-20 13:38:00.000  2010-07-20 13:45:00.000   
26       28.0  2010-07-27 04:12:00.000  2010-07-27 04:24:00.000   
27       29.0  2010-07-28 20:33:00.000  2010-07-28 20:42:00.000   
28       30.0  2010-08-01 07:55:00.000  2010-08-01 08:26:00.000   
29       31.0  2010-08-05 20:39:00.000  2010-08-05 21:35:00.000   
...       ...                      ...                      ...   
4740   5030.0  2014-04-13 22:11:00.000  2014-04-13 22:16:00.000   
4741   5031.0  2014-04-13 23:46:00.000  2014-04-13 23:52:00.000   
4742   5032.0  2014-04-14 02:06:00.000  2014-04-14 02:11:00.000   
4743   5033.0  2014-04-14 04:18:00.000  2014-04-14 04:38:00.000   
4744   5034.0  2014-04-14 07:08:00.000  2014-04-14 07:12:00.000   
4745   5035.0  2014-04-14 07:49:00.000  2014-04-14 08:00:00.000   
4746   5036.0  2014-04-14 08:57:00.000  2014-04-14 09:00:00.000   
4747   5037.0  2014-04-14 08:57:00.000  2014-04-14 09:00:00.000   
4748   5038.0  2014-04-14 09:06:00.000  2014-04-14 09:12:00.000   
4749   5039.0  2014-04-14 09:25:00.000  2014-04-14 09:27:00.000   
4750   5040.0  2014-04-14 10:45:00.000  2014-04-14 10:57:00.000   
4751   5041.0  2014-04-14 12:17:00.000  2014-04-14 12:29:00.000   
4752   5042.0  2014-04-14 15:30:00.000  2014-04-14 15:45:00.000   
4753   5043.0  2014-04-14 18:14:00.000  2014-04-14 18:17:00.000   
4754   5044.0  2014-04-14 19:42:00.000  2014-04-14 19:45:00.000   
4755   5045.0  2014-04-15 03:10:00.000  2014-04-15 03:17:00.000   
4756   5046.0  2014-04-15 05:49:00.000  2014-04-15 05:56:00.000   
4757   5047.0  2014-04-15 06:31:00.000  2014-04-15 06:36:00.000   
4758   5048.0  2014-04-15 06:42:00.000  2014-04-15 06:47:00.000   
4759   5049.0  2014-04-15 07:04:00.000  2014-04-15 07:09:00.000   
4760   5050.0  2014-04-15 08:53:00.000  2014-04-15 08:57:00.000   
4761   5051.0  2014-04-15 09:15:00.000  2014-04-15 09:23:00.000   
4762   5052.0  2014-04-15 09:53:00.000  2014-04-15 09:57:00.000   
4763   5053.0  2014-04-15 12:34:00.000  2014-04-15 12:46:00.000   
4764   5054.0  2014-04-15 13:22:00.000  2014-04-15 13:26:00.000   
4765   5055.0  2014-04-15 17:53:00.000  2014-04-15 17:59:00.000   
4766   5056.0  2014-04-15 23:43:00.000  2014-04-15 23:49:00.000   
4767   5057.0  2014-04-16 01:10:00.000  2014-04-16 01

In [200]:
jedi_sub_noNaN_events = jedi_sub_copy.dropna(thresh=8)

In [204]:
jedi_sub_noNaN_events

Event #    GOES Flare Start Time     GOES Flare Peak Time  \
3         4.0  2010-05-05 17:13:00.000  2010-05-05 17:19:00.000   
7         9.0  2010-06-12 00:30:00.000  2010-06-12 00:57:00.000   
8        10.0  2010-06-12 03:57:00.000  2010-06-12 04:06:00.000   
9        11.0  2010-06-12 09:02:00.000  2010-06-12 09:17:00.000   
16       18.0  2010-06-13 10:47:00.000  2010-06-13 10:53:00.000   
17       19.0  2010-06-14 00:44:00.000  2010-06-14 00:51:00.000   
18       20.0  2010-07-08 22:03:00.000  2010-07-08 22:16:00.000   
19       21.0  2010-07-09 08:53:00.000  2010-07-09 09:01:00.000   
21       23.0  2010-07-13 10:43:00.000  2010-07-13 10:51:00.000   
22       24.0  2010-07-14 12:11:00.000  2010-07-14 12:30:00.000   
25       27.0  2010-07-20 13:38:00.000  2010-07-20 13:45:00.000   
26       28.0  2010-07-27 04:12:00.000  2010-07-27 04:24:00.000   
27       29.0  2010-07-28 20:33:00.000  2010-07-28 20:42:00.000   
28       30.0  2010-08-01 07:55:00.000  2010-08-01 08:26:00.000   
29       31.0  2010-08-05 20:39:00.000  2010-08-05 21:35:00.000   
30       32.0  2010-08-07 17:55:00.000  2010-08-07 18:24:00.000   
31       33.0  2010-08-14 09:38:00.000  2010-08-14 10:05:00.000   
32       34.0  2010-08-14 18:03:00.000  2010-08-14 18:08:00.000   
36       38.0  2010-08-18 04:45:00.000  2010-08-18 05:48:00.000   
37       38.0  2010-08-18 04:45:00.000  2010-08-18 05:48:00.000   
39       40.0  2010-09-08 23:05:00.000  2010-09-08 23:33:00.000   
40       41.0  2010-09-17 01:17:00.000  2010-09-17 01:22:00.000   
44       45.0  2010-09-21 07:38:00.000  2010-09-21 07:53:00.000   
45       45.0  2010-09-21 07:38:00.000  2010-09-21 07:53:00.000   
46       45.0  2010-09-21 07:38:00.000  2010-09-21 07:53:00.000   
48       47.0  2010-09-28 22:05:00.000  2010-09-28 22:11:00.000   
49       47.0  2010-09-28 22:05:00.000  2010-09-28 22:11:00.000   
50       47.0  2010-09-28 22:05:00.000  2010-09-28 22:11:00.000   
51       48.0  2010-10-04 16:28:00.000  2010-10-04 16:35:00.000   
52       48.0  2010-10-04 16:28:00.000  2010-10-04 16:35:00.000   
...       ...                      ...                      ...   
4545   4833.0  2014-03-12 07:21:00.000  2014-03-12 07:57:00.000   
4547   4835.0  2014-03-12 17:20:00.000  2014-03-12 17:40:00.000   
4548   4836.0  2014-03-12 22:28:00.000  2014-03-12 22:34:00.000   
4551   4839.0  2014-03-13 19:03:00.000  2014-03-13 19:19:00.000   
4554   4842.0  2014-03-14 05:46:00.000  2014-03-14 05:52:00.000   
4555   4843.0  2014-03-14 08:32:00.000  2014-03-14 10:21:00.000   
4556   4844.0  2014-03-15 00:20:00.000  2014-03-15 00:26:00.000   
4560   4848.0  2014-03-15 09:30:00.000  2014-03-15 09:40:00.000   
4562   4850.0  2014-03-15 17:06:00.000  2014-03-15 17:15:00.000   
4565   4853.0  2014-03-16 08:06:00.000  2014-03-16 08:13:00.000   
4630   4918.0  2014-03-25 08:05:00.000  2014-03-25 08:08:00.000   
4632   4920.0  2014-03-26 00:35:00.000  2014-03-26 00:54:00.000   
4633   4921.0  2014-03-26 03:18:00.000  2014-03-26 03:26:00.000   
4638   4926.0  2014-03-27 00:27:00.000  2014-03-27 00:37:00.000   
4639   4927.0  2014-03-27 20:20:00.000  2014-03-27 20:29:00.000   
4640   4928.0  2014-03-28 12:55:00.000  2014-03-28 13:12:00.000   
4647   4935.0  2014-03-28 23:44:00.000  2014-03-28 23:51:00.000   
4652   4940.0  2014-03-29 07:50:00.000  2014-03-29 08:00:00.000   
4662   4950.0  2014-03-29 21:41:00.000  2014-03-29 22:48:00.000   
4668   4956.0  2014-03-30 08:07:00.000  2014-03-30 08:26:00.000   
4669   4957.0  2014-03-30 11:48:00.000  2014-03-30 11:55:00.000   
4676   4964.0  2014-03-31 04:01:00.000  2014-03-31 04:11:00.000   
4677   4965.0  2014-03-31 07:20:00.000  2014-03-31 08:07:00.000   
4682   4970.0  2014-04-01 00:43:00.000  2014-04-01 00:50:00.000   
4714   5002.0  2014-04-05 10:40:00.000  2014-04-05 10:50:00.000   
4719   5008.0  2014-04-07 06:22:00.000  2014-04-07 06:31:00.000   
4721   5011.0  2014-04-08 23:58:00.000  2014-04-09 00:04:00.000   
4722   5012.0  2014-04-09 18:08:00.000  2014-04-09 18

In [203]:
jedi_sub_noNaN_events.filter(like='Depth').T.describe()

3         7         8         9         16       17        18    \
count  1.000000  1.000000  2.000000  2.000000  2.000000  1.00000  1.000000   
mean   0.093239  0.420038  0.477681  0.170785  0.682448  0.00583  0.332573   
std         NaN       NaN  0.598248  0.091795  0.793928      NaN       NaN   
min    0.093239  0.420038  0.054656  0.105876  0.121056  0.00583  0.332573   
25%    0.093239  0.420038  0.266169  0.138331  0.401752  0.00583  0.332573   
50%    0.093239  0.420038  0.477681  0.170785  0.682448  0.00583  0.332573   
75%    0.093239  0.420038  0.689194  0.203239  0.963144  0.00583  0.332573   
max    0.093239  0.420038  0.900706  0.235694  1.243839  0.00583  0.332573   

           19        21        22      ...         4669      4676      4677  \
count  1.000000  2.000000  3.000000    ...     1.000000  1.000000  1.000000   
mean   0.570929  0.969494  0.862911    ...     2.029286  1.679126  2.471866   
std         NaN  0.410568  1.048349    ...          NaN       NaN       NaN   
min    0.570929  0.679178  0.038258    ...     2.029286  1.679126  2.471866   
25%    0.570929  0.824336  0.273017    ...     2.029286  1.679126  2.471866   
50%    0.570929  0.969494  0.507776    ...     2.029286  1.679126  2.471866   
75%    0.570929  1.114652  1.275237    ...     2.029286  1.679126  2.471866   
max    0.570929  1.259809  2.042699    ...     2.029286  1.679126  2.471866   

           4682      4714      4719      4721      4722      4723      4736  
count  1.000000  4.000000  1.000000  1.000000  1.000000  2.000000  1.000000  
mean   3.070594  0.620604  0.325991  0.245076  0.971861  0.989749  0.338004  
std         NaN  0.367427       NaN       NaN       NaN  0.407547       NaN  
min    3.070594  0.166979  0.325991  0.245076  0.971861  0.701570  0.338004  
25%    3.070594  0.420892  0.325991  0.245076  0.971861  0.845660  0.338004  
50%    3.070594  0.650151  0.325991  0.245076  0.971861  0.989749  0.338004  
75%    3.070594  0.849863  0.325991  0.245076  0.971861  1.133839  0.338004  
max    3.070594  1.015135  0.325991  0.245076  0.971861  1.277929  0.338004  

[8 rows x 1178 columns]

In [213]:
jedi_sub_noNaN_events.to_csv(path_or_buf='jedi_condensed.csv', index=False)